#!/usr/bin/env python3
"""
Assemble the Hugging Face Space for the Preventra API.

WHY A SEPARATE SPACE REPO
-------------------------
This repository is ~117 MB of git history, most of it parquet and CSV that the
API never opens. A Space that builds from it would clone all of that on every
deploy. What the service actually reads at runtime is under 1 MB, so the Space
gets its own repository containing exactly that and nothing else.

Run this, then push the output directory to the Space remote. Re-run it after
changing api/ or models/ and push again - it is idempotent and always rebuilds
from the current working tree, so the Space cannot drift from this repo.

    python scripts/build_hf_space.py
    cd build/hf-space && git add -A && git commit -m "Deploy" && git push
"""
from __future__ import annotations

import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "build", "hf-space")

# Python packages the service imports. models/ is copied whole because
# api/main.py imports four of its modules; the training scripts alongside them
# are inert (never imported) and add a few hundred KB.
PACKAGES = ["api", "models"]

# The only data files read at runtime. Everything else beside them is training
# output. api/mimic_scoring.py resolves these paths, so the layout must match
# the repository exactly.
DATA_FILES = [
    "data/mimic/model/results/phase1_model.joblib",
    "data/mimic/model/results/mimic_feature_spec.json",
    # Backs /api/model/metrics. Its handler returns 503 rather than inventing
    # figures when the card is missing, so leaving it out takes Analytics down.
    "data/mimic/model/results/model_card_phase1.json",
    "docs/mimic/band_thresholds_mimic.json",
]

ROOT_FILES = ["requirements-api.txt"]

# HF Spaces serves on 7860 and reads its configuration from this frontmatter.
SPACE_README = """---
title: Preventra API
emoji: 🩺
colorFrom: blue
colorTo: indigo
sdk: docker
app_port: 7860
pinned: false
---

# Preventra API

FastAPI backend for the Preventra readmission-risk dashboard. Serves the
patient worklist, risk scoring and analytics consumed by the frontend.

Generated by `scripts/build_hf_space.py` in the Preventra repository — edit it
there, not here.

## Required secrets

Set these under **Settings → Variables and secrets**. The Space will not start
without `MONGO_URI`.

| Secret | Purpose |
|---|---|
| `MONGO_URI` | MongoDB Atlas connection string |
| `API_KEY` | Value clients must send as the `X-API-Key` header |
| `GEMINI_API_KEY` | ROI insights, week narratives and the chatbot |
| `ALLOWED_ORIGINS` | Comma-separated origins allowed to call the API |

MongoDB Atlas must allow inbound connections from `0.0.0.0/0` — Spaces have no
fixed egress IP.

## Health

`GET /healthz` returns `{"status": "ok"}` without an API key.
"""

DOCKERFILE = """# syntax=docker/dockerfile:1
FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    PIP_NO_CACHE_DIR=1

# Spaces run the container as uid 1000. Create the user and the working tree as
# root first: a WORKDIR that does not exist yet is created root-owned even when
# it follows USER, and a later mkdir as an unprivileged user then fails.
RUN useradd -m -u 1000 user \\
 && mkdir -p /home/user/app/data/input \\
 && chown -R user:user /home/user/app

USER user
ENV PATH=/home/user/.local/bin:$PATH
WORKDIR /home/user/app

# Dependencies first so a code change does not reinstall pandas and shap.
COPY --chown=user:user requirements-api.txt .
RUN pip install --no-cache-dir --user -r requirements-api.txt

COPY --chown=user:user api/ ./api/
COPY --chown=user:user models/ ./models/
COPY --chown=user:user data/ ./data/
COPY --chown=user:user docs/ ./docs/

# Spaces route traffic to 7860.
ENV PORT=7860
EXPOSE 7860
CMD ["sh", "-c", "uvicorn api.main:app --host 0.0.0.0 --port ${PORT}"]
"""



def main() -> int:
    # Clear the output, but never .git. The Space is its own git repository
    # living in this directory; a blanket rmtree would delete its history and
    # its remote, and the next `git commit` run from here would silently apply
    # to the parent repository instead.
    os.makedirs(OUT, exist_ok=True)
    for entry in os.listdir(OUT):
        if entry == ".git":
            continue
        target = os.path.join(OUT, entry)
        shutil.rmtree(target) if os.path.isdir(target) else os.remove(target)

    for pkg in PACKAGES:
        shutil.copytree(
            os.path.join(ROOT, pkg), os.path.join(OUT, pkg),
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "*.ipynb"))

    for rel in DATA_FILES:
        dest = os.path.join(OUT, rel)
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        shutil.copy2(os.path.join(ROOT, rel), dest)

    for rel in ROOT_FILES:
        shutil.copy2(os.path.join(ROOT, rel), os.path.join(OUT, rel))

    open(os.path.join(OUT, "README.md"), "w").write(SPACE_README)
    open(os.path.join(OUT, "Dockerfile"), "w").write(DOCKERFILE)

    # A .env copied into the Space would put live credentials in a public git
    # history. Secrets belong in the Space's own settings.
    for stray in (".env", ".env.bak"):
        path = os.path.join(OUT, stray)
        if os.path.exists(path):
            os.remove(path)

    # Count the payload only - .git is the Space's own history, not content
    # being deployed, and including it makes the figure meaningless.
    total = count = 0
    for dirpath, dirnames, files in os.walk(OUT):
        dirnames[:] = [d for d in dirnames if d != ".git"]
        count += len(files)
        total += sum(os.path.getsize(os.path.join(dirpath, f)) for f in files)
    print(f"built {OUT}")
    print(f"{count} files, {total / 1024 / 1024:.1f} MB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
