/*
 * Generates the deployable portal into dist/.
 *
 * The portal is a static page with no framework, so it cannot read environment
 * variables at runtime the way the two Vite apps do - by the time the browser
 * has the page, the build environment is long gone. This script closes that
 * gap: it copies the static files and writes config.js from the environment, so
 * the deployed URLs live in Vercel's project settings alongside every other
 * service's, and no origin is committed to the repository.
 *
 * Local development does not need this. `npx serve Portal` serves the committed
 * config.js, which points at localhost.
 *
 * Run: node build.js   (Vercel: build command `npm run build`, output `dist`)
 */
const fs = require('node:fs');
const path = require('node:path');

const SRC = __dirname;
const OUT = path.join(SRC, 'dist');

// Build machinery and anything secret-adjacent. Everything else in this folder
// is a static asset the page may reference.
const EXCLUDE = new Set(['build.js', 'package.json', 'package-lock.json',
                         'node_modules', 'dist', 'config.js', '.vercel']);

const env = (name, fallback) => {
  const value = (process.env[name] || '').trim().replace(/\/$/, '');
  if (!value) {
    console.warn(`  !  ${name} is not set - falling back to ${fallback || '(blank)'}`);
    return fallback;
  }
  return value;
};

const AUTH_BASE_URL = env('PORTAL_AUTH_BASE_URL', 'http://localhost:8001');
const GLP1_URL = env('PORTAL_GLP1_URL', '');
const READMISSIONS_URL = env('PORTAL_READMISSIONS_URL', '');

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

for (const entry of fs.readdirSync(SRC)) {
  if (EXCLUDE.has(entry) || entry.startsWith('.')) continue;   // no dotfiles in a public bundle
  fs.cpSync(path.join(SRC, entry), path.join(OUT, entry), { recursive: true });
  console.log(`  +  ${entry}`);
}

// A blank url leaves the tile visible but marked unconfigured, which is the
// honest failure: the page says what is missing instead of navigating nowhere.
const config = `// GENERATED BY build.js - do not edit, and do not commit dist/.
window.__PORTAL_CONFIG__ = ${JSON.stringify({
  AUTH_BASE_URL,
  APPS: [
    {
      key: 'glp1',
      name: 'GLP-1 Analytics',
      blurb: 'Treatment response, adherence and payer return on investment.',
      url: GLP1_URL,
      handoff: 'fragment',
    },
    {
      key: 'readmissions',
      name: 'Readmission Risk',
      blurb: 'Discharge risk scoring, weekly monitoring and the clinician console.',
      url: READMISSIONS_URL,
      handoff: 'fragment',
    },
  ],
}, null, 2)};
`;
fs.writeFileSync(path.join(OUT, 'config.js'), config);
console.log(`  +  config.js (auth: ${AUTH_BASE_URL})`);
console.log('✓  portal built into dist/');
